# Generated by Django 2.2.24 on 2022-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pads',
            fields=[
                ('pad_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(default='None', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('active_since', models.DateTimeField()),
            ],
        ),
    ]
